# @package _global_
defaults:
  - default
  - /collator@datamodule.dataset_managers.train.lm.collator: seq2seq_lflexmdm
  - /collator@datamodule.dataset_managers.val.lm.collator: seq2seq_lflexmdm
  - /collator@datamodule.dataset_managers.test.lm.collator: seq2seq_lflexmdm
  - /collator@datamodule.dataset_managers.val.prediction.collator: seq2seq_pred_lflexmdm
  - /collator@datamodule.dataset_managers.test.prediction.collator: seq2seq_pred_lflexmdm
  - /collator@datamodule.dataset_managers.predict.prediction.collator: seq2seq_pred_lflexmdm

datamodule:
  print_batch_fn: lflexmdm.datamodule_flexmdm.print_batch_flexmdm

tags:
  dataset: ???
